name: neoMc-Plugin
main: com.neocop.roleplayplugin.Core.Plugin
version: 1.2
author: Neo_Mc Noah Elijah Till
api-version: 1.13
commands:
    helloWorld:
        description: just Hello World...yk?
        usage: /<command> 
    rpg:
        description: configure all rpg stuff
        usage: /<command> help - fuer mehr Hilfe
    detectiv:
        description: for the role Detectiv
        usage: /<command> help - helps with the <command> command
    troll:
        description: lool
        usage: /<command> [mod] [player] - troll player
    util:
        desciption: has some helpful commands
        usage: /<command> help - for more help
    port:
        desciption: port command
        usage: /<command> help - for more help