name: roleplayPlugin
main: com.neocop.roleplayplugin.Core.Main
version: 1.0
author: Neo_Mc Noah Elijah Till
commands:
    helloWorld:
        description: just Hello World...yk?
        usage: /<command> 
    rpg:
        description: configure all rpg stuff
        usage: /<command> help - fuer mehr Hilfe
    detectiv:
        description: for the role Detectiv
        usage: /<command> help - helps with the <command> command
    vote:
        description: to vote which player should die
        usage: /<command> [player] - vote for one player
    troll:
        description: lool
        usage: /<command> [mod] [player] - troll player